version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: user_db
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3307:3306" # Change host port to 3307 to avoid conflict
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: node_app
    environment:
      DB_HOST: db
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_NAME: user_db
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
